version: '0.1'
services:
  rest-service:
    container_name: rest_service
    build: ./
    restart: always
    ports:
      - "9090:9090"
  profile-service:
    container_name: profile-service
    build: ../profile-service
    restart: always
    ports:
      - "9091:9091"
  
